# Generated by Django 3.2 on 2021-04-17 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupProduct', models.CharField(max_length=50, verbose_name='نام آیتم')),
                ('groupProduct_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': ' گروه محصول',
                'verbose_name_plural': ' گروه محصولات',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, verbose_name='نام آیتم')),
                ('item_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': ' ایتم',
                'verbose_name_plural': '  آیتم ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('groupProduct', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='store.groupproduct', verbose_name='گروه محصولات')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='نام مشتری')),
                ('customer_family', models.CharField(max_length=50, verbose_name='نام خانوادگی مشتری')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
    ]
